# -*- coding: utf-8 -*-
"""QuizRW_1301180174.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ShaqKVdAP_Qz85041XketX0RFX1WsTdg
"""

import numpy 
import pylab 
import random 
  
print("Dani Andhika Permana")
print("1301180174")
print("")

print("a.")
print("#kanan 2x kiri, bawah 2x atas, atas 2x kiri")
print("Peluang ke kanan = 2/9")
print("Peluang ke kiri  = 1/9")
print("Peluang ke atas  = 2/9")
print("Peluang ke bawah = 4/9")
print("")

print("b.")
n = 101 #100 iterasi
m = 11 #10 titik

for j in range(1,m):
  x = numpy.zeros(n) 
  y = numpy.zeros(n) 

  x[0] = j
  y[0] = j
  
  if j != 10:
    print("Titik Awal ke "+str(j)+"  : "+str(x[0])+" , "+str(y[0]))
  else:
    print("Titik Awal ke "+str(j)+" : "+str(x[0])+", "+str(y[0]))
    
  #koordinat random 4 arah
  for i in range(1, n): 
      arah = [1,1,2,3,3,4,4,4,4] #kanan 2x kiri, bawah 2x atas, atas 2x kiri
      val = random.choice(arah)
      if val == 1:                #kanan
          x[i] = x[i - 1] + 1
          y[i] = y[i - 1] 
      elif val == 2:              #kiri
          x[i] = x[i - 1] - 1
          y[i] = y[i - 1] 
      elif val == 3:              #atas
          x[i] = x[i - 1] 
          y[i] = y[i - 1] + 1
      else:                       #bawah
          x[i] = x[i - 1] 
          y[i] = y[i - 1] - 1
        
    
  # plotting : 
  pylab.title("Random Walk (" + str(n-1) + " iterasi dan " + str(m-1) + " titik) ") 
  pylab.plot(x, y) 
  pylab.savefig("rand_walk"+str(n)+".png",bbox_inches="tight",dpi=600) 

pylab.show()

"""![alt text](https://imgur.com/6e4v1Jd.jpg)"""